# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python package

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  mypy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Python dependencies
        run: pip install mypy -r requirements.txt
      - name: Mypy
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: mypy
          run: mypy --show-column-numbers .

  pytest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Test with pytest
        run: pytest
